# Generated by Django 4.2.7 on 2023-11-05 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_expert_staff_problem_notification_fileattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileattachment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.staff'),
        ),
    ]
