# Generated by Django 4.2.7 on 2023-11-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_otp_alter_comment_rating_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='admin_notified',
            field=models.BooleanField(default=False),
        ),
    ]
