# Generated by Django 4.2.7 on 2023-11-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_problem_admin_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
