# Generated by Django 4.2.7 on 2023-11-19 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_expert_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileattachment',
            name='file_path',
            field=models.FileField(upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='fileattachment',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='helpdesk.problem'),
        ),
    ]
